0_poison_epochs: [27]
0_poison_pattern:
- [0, 0]
- [1, 0]
- [0, 1]
- [1, 1]
- [0, 2]
- [1, 2]
- [0, 3]
- [1, 3]
- [0, 4]
- [1, 4]
- [0, 5]
- [1, 5]
- [0, 6]
- [1, 6]
- [0, 7]
- [1, 7]
- [0, 8]
- [1, 8]
- [0, 9]
- [1, 9]
- [0, 12]
- [1, 12]
- [0, 13]
- [1, 13]
- [0, 14]
- [1, 14]
- [0, 15]
- [1, 15]
- [0, 16]
- [1, 16]
- [0, 17]
- [1, 17]
- [0, 18]
- [1, 18]
- [0, 19]
- [1, 19]
- [0, 20]
- [1, 20]
- [0, 21]
- [1, 21]
- [4, 0]
- [5, 0]
- [4, 1]
- [5, 1]
- [4, 2]
- [5, 2]
- [4, 3]
- [5, 3]
- [4, 4]
- [5, 4]
- [4, 5]
- [5, 5]
- [4, 6]
- [5, 6]
- [4, 7]
- [5, 7]
- [4, 8]
- [5, 8]
- [4, 9]
- [5, 9]
- [4, 12]
- [5, 12]
- [4, 13]
- [5, 13]
- [4, 14]
- [5, 14]
- [4, 15]
- [5, 15]
- [4, 16]
- [5, 16]
- [4, 17]
- [5, 17]
- [4, 18]
- [5, 18]
- [4, 19]
- [5, 19]
- [4, 20]
- [5, 20]
- [4, 21]
- [5, 21]
adversary_list: [17]
aggr_epoch_interval: 1
aggregation_methods: foolsgold
alpha_loss: 1
baseline: false
batch_size: 64
batch_track_distance: false
centralized_test_trigger: true
current_time: Jun.19_08.25.49
decay: 0.0005
diff_privacy: true
dirichlet_alpha: 0.01
environment_name: tiny
epochs: 100
eta: 0.1
fg_use_memory: true
folder_path: saved_models/model_tiny_Jun.19_08.25.49
geom_median_maxiter: 10
internal_epochs: 2
internal_poison_epochs: 10
is_poison: true
is_random_adversary: false
is_random_namelist: true
log_interval: 2
lr: 0.001
momentum: 0.9
no_models: 10
number_of_total_participants: 100
participants_namelist: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
poison_decay: 0.005
poison_epochs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
  20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
  40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
  60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
  80]
poison_label_swap: 2
poison_lr: 0.001
poison_momentum: 0.9
poison_step_lr: true
poisoning_per_batch: 20
results_json: true
resumed_model: false
resumed_model_name: tiny_64_pretrain/tiny-resnet.epoch_20
resumed_model_path: tiny_64_pretrain/
s_norm: 1000000
sampling_dirichlet: true
save_model: true
save_on_epochs: [40, 41, 42, 50, 60]
scale_weights_poison: 100
sigma: 0.01
test_batch_size: 64
track_distance: false
trigger_num: 1
type: tiny-imagenet-200
vis_train: true
vis_train_batch_loss: true
vis_trigger_split_test: true
