---
type: tiny-imagenet-200
test_batch_size: 64
lr: 0.001
poison_lr: 0.001
momentum: 0.9
decay: 0.0005
batch_size: 64
epochs: 100
internal_epochs: 2
internal_poison_epochs: 10 # multi-shot: 5; single-shot: 10
poisoning_per_batch: 40 # 20
aggr_epoch_interval: 1
# aggregation_methods Allowed values are: [ 'mean', 'geom_median','foolsgold']
aggregation_methods: 'geom_median'
fg_use_memory: true
participants_namelist: [0,1,2,3,4,5,6,7,8,9]
geom_median_maxiter: 10
no_models: 10
number_of_total_participants: 100
is_random_namelist: true
is_random_adversary: false
is_poison: true

baseline: false # single-shot: false; multi-shot: true
scale_weights_poison: 100
#global lr:
eta: 0.1 # multishot: 1 ;singleshot: 0.1
sampling_dirichlet: true
dirichlet_alpha: 0.01

# distributed attackers: (training img num : 990 - 993 -  983 - 993 )
adversary_list: [0, 3, 5, 9, 10, 12, 15, 18, 20, 24, 25, 30, 33, 36, 37, 42, 44, 48, 49, 54, 55, 60, 61, 65, 69, 72, 74, 78, 81, 84, 85, 95]
# centralized attackers: (training img num : 999)
#adversary_list: [17]

centralized_test_trigger: true
trigger_num: 32

### gap 2 size 2*10 base 0
0_poison_pattern: [[0, 0], [1, 0], [0, 1], [1, 1]]
1_poison_pattern: [[0, 12], [1, 12], [0, 13], [1, 13]]
2_poison_pattern: [[4, 0], [5, 0], [4, 1], [5, 1]]
3_poison_pattern: [[4, 12], [5, 12], [4, 13], [5, 13]]
4_poison_pattern: [[0, 5], [1, 5], [0, 6], [1, 6]]
5_poison_pattern: [[0, 17], [1, 17], [0, 18], [1, 18]]
6_poison_pattern: [[4, 5], [5, 5], [4, 6], [5, 6]]
7_poison_pattern: [[4, 17], [5, 17], [4, 18], [5, 18]]
8_poison_pattern: [[0, 3], [1, 3]]
9_poison_pattern: [[0, 15], [1, 15]]
10_poison_pattern: [[4, 3], [5, 3]]
11_poison_pattern: [[4, 15], [5, 15]]
12_poison_pattern: [[0, 8], [1, 8]]
13_poison_pattern: [[0, 20], [1, 20]]
14_poison_pattern: [[4, 8], [5, 8]]
15_poison_pattern: [[4, 20], [5, 20]]
16_poison_pattern: [[0, 2], [1, 2]]
17_poison_pattern: [[0, 14], [1, 14]]
18_poison_pattern: [[4, 2], [5, 2]]
19_poison_pattern: [[4, 14], [5, 14]]
20_poison_pattern: [[0, 7], [1, 7]]
21_poison_pattern: [[0, 19], [1, 19]]
22_poison_pattern: [[4, 7], [5, 7]]
23_poison_pattern: [[4, 19], [5, 19]]
24_poison_pattern: [[0, 4], [1, 4]]
25_poison_pattern: [[0, 16], [1, 16]]
26_poison_pattern: [[4, 4], [5, 4]]
27_poison_pattern: [[4, 16], [5, 16]]
28_poison_pattern: [[0, 9], [1, 9]]
29_poison_pattern: [[0, 21], [1, 21]]
30_poison_pattern: [[4, 9], [5, 9]]
31_poison_pattern: [[4, 21], [5, 21]]

0_poison_epochs: [21]
1_poison_epochs: [23]
2_poison_epochs: [25]
3_poison_epochs: [27]
4_poison_epochs: [29]
5_poison_epochs: [31]
6_poison_epochs: [33]
7_poison_epochs: [35]
8_poison_epochs: [37]
9_poison_epochs: [39]
10_poison_epochs: [41]
11_poison_epochs: [43]
12_poison_epochs: [45]
13_poison_epochs: [47]
14_poison_epochs: [49]
15_poison_epochs: [51]
16_poison_epochs: [53]
17_poison_epochs: [55]
18_poison_epochs: [57]
19_poison_epochs: [59]
20_poison_epochs: [61]
21_poison_epochs: [63]
22_poison_epochs: [65]
23_poison_epochs: [67]
24_poison_epochs: [69]
25_poison_epochs: [71]
26_poison_epochs: [73]
27_poison_epochs: [75]
28_poison_epochs: [77]
29_poison_epochs: [79]
30_poison_epochs: [81]
31_poison_epochs: [83]
#0_poison_epochs: [27]

poison_label_swap: 2
environment_name: tiny
save_model: true
save_on_epochs: [40,41,42,50,60]
resumed_model: false
resumed_model_name: tiny_64_pretrain/tiny-resnet.epoch_20
resumed_model_path: tiny_64_pretrain/

vis_train: true
vis_train_batch_loss: true
vis_trigger_split_test: true
track_distance: false
batch_track_distance: false
log_interval: 2
alpha_loss: 1
s_norm: 1000000
diff_privacy: false
sigma: 0.01
poison_momentum: 0.9
poison_decay: 0.005
poison_step_lr: true

results_json: true
poison_epochs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
                21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
                41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58 ,59, 60,
                61, 62, 63, 64, 65, 66, 67, 68, 69, 70,71, 72, 73, 74, 75, 76, 77, 78 ,79, 80]
